### ISSUE TITLE
Homework#4 what is false if I transmit ownership I don't possess

### ISSUE THREAD

**Issue by staufga0** [cui-unige/semantique#27]
if I have the following code in Ansem : 
let x = 2
let y &- x
let z <- y

 z cannot be properly assigned so it is false, but should I also say that y is misused and false ?

**Comment by saucisson** [comment]
@kyouko-taiga is it correct in Anzen?

**Comment by QuentinRiv** [comment]
If I correctly understood how it works, there is no error here.

`let x = 2` creates the object 2, makes a reference of `x` on `2`, and `x` becomes the owner of this object.
`let y &- x` makes a reference between `y` and the `x`'s object, `2` here (so there is a reference of `y` on `2`)
And `let z <- y` makes a reference of `z` on `2`, as before, and `z` becomes the new owner of `2`, (so not `x` anymore)

**Comment by saucisson** [comment]
Yes, here are an example where there is an error.

```
{
  let x = 2
  let y &- x
  let z <- x
} // here x, y and z are all deleted at the end of the block, so there is no erroneous reference to the value 2
```
`x,y,z` are marked as `true` in the results table.

```
let x = 2
let y &- x
{
  let z <- x
} // here z is deleted at the end of the block, and thus also deleted the value 2, because it owns it
// x and y both refer to the deleted value 2, and are thus in error
```
`x,y` are marked as `false` in the results table, `z` is marked as `true`.

**Comment by QuentinRiv** [comment]
Moreover, 2 examples :
`let x = 2  // Creates the object 2, makes a reference of x on 2, whose x is the owner `
`let y = x  // Create a new object 2 (different from the previous 2), makes a reference on this new object, and y is the owner of this one `

And :
`let z <- x + 1   // Correct, because x exists, so here, it evaluates x+1, makes a new object of it, and makes a reference of z on this new object, whose z is the owner`
`let w &- x + 1   // Incorrect, because there is no owner of the new object x+1, so this object cannot exist, and so w reference on nothing existing`

**Comment by saucisson** [comment]
You are right, `z` cannot get ownership because `y` does not have ownership.

**Comment by staufga0** [comment]
so, should I say that y is false, because it's used in a wrong manner, or only z is false ?

**Comment by saucisson** [comment]
You should say that `y` is `false`, and `z` is `false`.

**Comment by staufga0** [comment]
Ok, thank You
