### ISSUE TITLE
Is type correctness important in TP4?

### ISSUE THREAD

**Issue by consolethinks** [cui-unige/semantique#31]
Is type correctness important in TP4 or is it enough to check in a BindingStatement if all the referenced variables already exist, and of course when we change ownership etc.?

**Comment by saucisson** [comment]
You can suppose safely that  type checking has been performed and is correct. You must only check what is required for this homework.

**Comment by attilaM68K** [comment]
So suppose we have this:
let x = 2
let y = false
let z = x + y
So z should be true, because we've referenced 2 pre-exisiting variables, and even if their types are incorrect, it's not the job of this TP to check against that?
Also, then a false case would be the following then:
let x = 2
let z = x + y
because y doesn't exist.

**Comment by saucisson** [comment]
Yes, `z` should be true in the first case, and false in the second one.
